import Device
#import EditPointScreen
from com.android.monkeyrunner import MonkeyRunner, MonkeyDevice, MonkeyImage

# Executa a aplicacao e retorna a mesma
application = Device.startActivity()

for x in xrange(1,11):
	try:
		print("Teste "+str(x))
		print("O aplicativo deve inserir um ponto atraves do botao bater ponto da barra de acoes")
		MonkeyRunner.sleep(2)
		application.touch(605, 100, 'DOWN_AND_UP')
		print("O aplicativo deve editar o segundo ponto tocando no mesmo")
		MonkeyRunner.sleep(2)
		application.touch(554, 350, 'DOWN_AND_UP')
		print("O aplicativo arrasta as horas da edicao")
		MonkeyRunner.sleep(2)
		application.drag((320,750),(320,470),0.15,5)
		print("O aplicativo arrasta os minutos da edicao")
		MonkeyRunner.sleep(2)
		application.drag((500,470),(500,750),0.15,5)
		print("O aplicativo clica em ok")
		MonkeyRunner.sleep(2)
		application.touch(380, 900, 'DOWN_AND_UP')
		print("O aplicativo troca para tela de lista de pontos")
		MonkeyRunner.sleep(2)
		application.drag((700,700),(25,700),0.15,5)
		print("Foto da lista de pontos")
		MonkeyRunner.sleep(2)
		photoListPoint = application.takeSnapshot()
		photoListPoint.writeToFile('./screenshots/listPoints/listPoint'+str(x)+'.png','png')
		MonkeyRunner.sleep(2)
		print("O aplicativo cria um novo ponto")
		MonkeyRunner.sleep(2)
		application.touch(605, 100, 'DOWN_AND_UP')
		print("O aplicativo seleciona a data do novo ponto")
		MonkeyRunner.sleep(2)
		application.drag((210,750),(210,470),0.15,5)
		print("O clica em ok")
		MonkeyRunner.sleep(2)
		application.touch(380, 900, 'DOWN_AND_UP')
	except Exception, e:
		print("Ocorreu um erro")
		erro = application.takeSnapshot()
		erro.writeToFile('./screenshots/errors/error'+str(x)+'.png','png')
pass
try:
	print("Pressionando botao back do device e voltando a tela de lista de pontos")
	MonkeyRunner.sleep(2)
	application.press("KEYCODE_BACK", MonkeyDevice.DOWN_AND_UP)
	print("Pressionando botao home do aplicativo e voltando a tela de edicao de pontos, porem nao decrementando o historico")
	MonkeyRunner.sleep(2)
	application.touch(60, 60, 'DOWN_AND_UP')
	print("Pressionando menu")
	MonkeyRunner.sleep(2)
	application.touch(730, 60, 'DOWN_AND_UP')
	print("Testando exportacoes")
	print("Pressionando menu")
	MonkeyRunner.sleep(2)
	application.touch(730, 60, 'DOWN_AND_UP')
	print("Pressionando para exportar")
	MonkeyRunner.sleep(2)
	application.touch(730, 165, 'DOWN_AND_UP')
	print("Selecionando formato .CSV")
	MonkeyRunner.sleep(2)
	application.touch(730, 165, 'DOWN_AND_UP')
	print("Pressionando em sim")
	MonkeyRunner.sleep(2)
	application.touch(555, 770, 'DOWN_AND_UP')
	MonkeyRunner.sleep(1)
	photoExportOk = application.takeSnapshot()
	photoExportOk.writeToFile('./screenshots/exports/exportCSV.png','png')
	print("Foto do ok da exportacao CSV")
	MonkeyRunner.sleep(2)
	print("Pressionando menu")
	MonkeyRunner.sleep(2)
	application.touch(730, 60, 'DOWN_AND_UP')
	print("Pressionando para exportar")
	MonkeyRunner.sleep(2)
	application.touch(730, 165, 'DOWN_AND_UP')
	print("Selecionando formato .json")
	MonkeyRunner.sleep(2)
	application.touch(660, 290, 'DOWN_AND_UP')
	print("Pressionando em sim")
	MonkeyRunner.sleep(2)
	application.touch(555, 770, 'DOWN_AND_UP')
	MonkeyRunner.sleep(1)
	photoExportOk = application.takeSnapshot()
	photoExportOk.writeToFile('./screenshots/exports/exportJSON.png','png')
	print("Foto do ok da exportacao JSON")
	MonkeyRunner.sleep(2)
except Exception, e:
	print("Ocorreu um erro durante a exportacao")
	erro = application.takeSnapshot()
	erro.writeToFile('./screenshots/errors/errorExport.png','png')


print("Testando decrementacao do historico")
for x in xrange(1,20):
	print("Teste "+str(x))
	print("Pressionando botao back do device")
	MonkeyRunner.sleep(2)
	application.press("KEYCODE_BACK", MonkeyDevice.DOWN_AND_UP)	
pass
